version: "3.7"
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_root
      MINIO_ROOT_PASSWORD: minio_root
      MINIO_API_ROOT_ACCESS: on
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    networks:
      delta-network:

  lakefs:
    image: quannadev/lakefs-minio
    container_name: lakefs
    environment:
      - ACCESS_KEY=lakefs_root
      - SECRET_ACCESS_KEY=lakefs_root
      - REPOSITORY=test
    ports:
      - "8000:8000"
    volumes:
      - ./lakefs.yaml:/app/config.yaml
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      delta-network:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      delta-network:

networks:
  delta-network:
    driver: bridge
  